name: First Workflow

on:
  push:
    branches: [ master ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Primer-Trabajo:
    runs-on: macos-latest

    steps:
      - name: Cambiando a la rama actual
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build and Run Maven
        run: |
          mvn clean install
          mvn test
         
         
      
          
